### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by Klatalk** [Klatalk/talkmarketing#3]
Just find content on our website to update documentation

**Comment by Superhuman07** [comment]
I can do that! 
Should I ?

**Comment by Klatalk** [comment]
I got help from a friend but yeah, you could take a look!

**Comment by Superhuman07** [comment]
ok sure 
Don't spam it if its not good ok 👍

**Comment by Klatalk** [comment]
All contributions are welcome, thanks.
